site_name: torchode
site_url: "https://torchode.readthedocs.org/"
repo_url: "https://github.com/martenlienen/torchode"
site_description: "A parallel ODE solver for PyTorch"

theme:
  name: material

plugins:
  - mkdocs-jupyter

nav:
  - "Introduction": README.md
  - jit.ipynb
  - torchdiffeq.ipynb
  - comparison.md
